// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvqbzjiwaftlsbbikuin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cWJ6aml3YWZ0bHNiYmlrdWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTU5ODgsImV4cCI6MjA3MzY3MTk4OH0.8QdZU0XENDMoC2Qs1CF1-qPMxoDDusOF7s3_qIXAW70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});